source 'http://rubygems.org'

gem 'rails', '3.2.5'

gem 'pg'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'devise'
gem "cancan"

gem 'activeadmin'

gem 'marginalia'

# Deploy with Capistrano
gem 'capistrano'

group :test, :development do
  gem 'rspec-rails'
  gem 'database_cleaner'
  gem 'factory_girl_rails'
  gem 'capybara'
  gem "cucumber-rails", "~> 1.3.0"
  gem 'fuubar'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-cucumber'
  gem 'guard-rspec'
  gem 'guard-pow'
  gem 'simplecov', '>= 0.5.3', :require => false
  gem 'simplecov-rcov', :require => false
end

group :development do
  gem 'hirb'
  gem 'bullet'
  gem 'rails-footnotes', '>= 3.7.8'
  gem 'rack-webconsole'
  gem 'sextant'
end

# To use debugger
# gem 'debugger'